# coding: utf-8

"""
    Accounting API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.accounting_api import AccountingApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAccountingApi(unittest.TestCase):
    """AccountingApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.accounting_api.AccountingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account(self):
        """Test case for create_account

        Allows you to create a new chart of accounts  # noqa: E501
        """
        pass

    def test_create_account_attachment_by_file_name(self):
        """Test case for create_account_attachment_by_file_name

        Allows you to create Attachment on Account  # noqa: E501
        """
        pass

    def test_create_bank_transaction(self):
        """Test case for create_bank_transaction

        Allows you to create a spend or receive money transaction  # noqa: E501
        """
        pass

    def test_create_bank_transaction_attachment_by_file_name(self):
        """Test case for create_bank_transaction_attachment_by_file_name

        Allows you to createa an Attachment on BankTransaction by Filename  # noqa: E501
        """
        pass

    def test_create_bank_transaction_history_record(self):
        """Test case for create_bank_transaction_history_record

        Allows you to create history record for a bank transactions  # noqa: E501
        """
        pass

    def test_create_bank_transfer(self):
        """Test case for create_bank_transfer

        Allows you to create a bank transfers  # noqa: E501
        """
        pass

    def test_create_bank_transfer_attachment_by_file_name(self):
        """Test case for create_bank_transfer_attachment_by_file_name

        """
        pass

    def test_create_bank_transfer_history_record(self):
        """Test case for create_bank_transfer_history_record

        """
        pass

    def test_create_batch_payment(self):
        """Test case for create_batch_payment

        Create one or many BatchPayments for invoices  # noqa: E501
        """
        pass

    def test_create_batch_payment_history_record(self):
        """Test case for create_batch_payment_history_record

        Allows you to create a history record for a Batch Payment  # noqa: E501
        """
        pass

    def test_create_branding_theme_payment_services(self):
        """Test case for create_branding_theme_payment_services

        Allow for the creation of new custom payment service for specified Branding Theme  # noqa: E501
        """
        pass

    def test_create_contact(self):
        """Test case for create_contact

        """
        pass

    def test_create_contact_attachment_by_file_name(self):
        """Test case for create_contact_attachment_by_file_name

        """
        pass

    def test_create_contact_group(self):
        """Test case for create_contact_group

        Allows you to create a contact group  # noqa: E501
        """
        pass

    def test_create_contact_group_contacts(self):
        """Test case for create_contact_group_contacts

        Allows you to add Contacts to a Contract Group  # noqa: E501
        """
        pass

    def test_create_contact_history(self):
        """Test case for create_contact_history

        Allows you to retrieve a history records of an Contact  # noqa: E501
        """
        pass

    def test_create_credit_note(self):
        """Test case for create_credit_note

        Allows you to create a credit note  # noqa: E501
        """
        pass

    def test_create_credit_note_allocation(self):
        """Test case for create_credit_note_allocation

        Allows you to create Allocation on CreditNote  # noqa: E501
        """
        pass

    def test_create_credit_note_attachment_by_file_name(self):
        """Test case for create_credit_note_attachment_by_file_name

        Allows you to create Attachments on CreditNote by file name  # noqa: E501
        """
        pass

    def test_create_credit_note_history(self):
        """Test case for create_credit_note_history

        Allows you to retrieve a history records of an CreditNote  # noqa: E501
        """
        pass

    def test_create_currency(self):
        """Test case for create_currency

        """
        pass

    def test_create_employee(self):
        """Test case for create_employee

        Allows you to create new employees used in Xero payrun  # noqa: E501
        """
        pass

    def test_create_expense_claim(self):
        """Test case for create_expense_claim

        Allows you to retrieve expense claims  # noqa: E501
        """
        pass

    def test_create_expense_claim_history(self):
        """Test case for create_expense_claim_history

        Allows you to create a history records of an ExpenseClaim  # noqa: E501
        """
        pass

    def test_create_invoice(self):
        """Test case for create_invoice

        Allows you to create any sales invoices or purchase bills  # noqa: E501
        """
        pass

    def test_create_invoice_attachment_by_file_name(self):
        """Test case for create_invoice_attachment_by_file_name

        Allows you to create an Attachment on invoices or purchase bills by it's filename  # noqa: E501
        """
        pass

    def test_create_invoice_history(self):
        """Test case for create_invoice_history

        Allows you to retrieve a history records of an invoice  # noqa: E501
        """
        pass

    def test_create_item(self):
        """Test case for create_item

        Allows you to create an item  # noqa: E501
        """
        pass

    def test_create_item_history(self):
        """Test case for create_item_history

        Allows you to create a history record for items  # noqa: E501
        """
        pass

    def test_create_linked_transaction(self):
        """Test case for create_linked_transaction

        Allows you to create linked transactions (billable expenses)  # noqa: E501
        """
        pass

    def test_create_manual_journal(self):
        """Test case for create_manual_journal

        Allows you to create a manual journal  # noqa: E501
        """
        pass

    def test_create_manual_journal_attachment_by_file_name(self):
        """Test case for create_manual_journal_attachment_by_file_name

        Allows you to create a specified Attachment on ManualJournal by file name  # noqa: E501
        """
        pass

    def test_create_overpayment_allocation(self):
        """Test case for create_overpayment_allocation

        Allows you to retrieve Allocations for overpayments  # noqa: E501
        """
        pass

    def test_create_overpayment_history(self):
        """Test case for create_overpayment_history

        Allows you to create history records of an Overpayment  # noqa: E501
        """
        pass

    def test_create_payment(self):
        """Test case for create_payment

        Allows you to create payments for invoices and credit notes  # noqa: E501
        """
        pass

    def test_create_payment_history(self):
        """Test case for create_payment_history

        Allows you to create a history record for a payment  # noqa: E501
        """
        pass

    def test_create_payment_service(self):
        """Test case for create_payment_service

        Allows you to create payment services  # noqa: E501
        """
        pass

    def test_create_prepayment_allocation(self):
        """Test case for create_prepayment_allocation

        Allows you to create an Allocation for prepayments  # noqa: E501
        """
        pass

    def test_create_prepayment_history(self):
        """Test case for create_prepayment_history

        Allows you to create a history record for an Prepayment  # noqa: E501
        """
        pass

    def test_create_purchase_order(self):
        """Test case for create_purchase_order

        Allows you to create purchase orders  # noqa: E501
        """
        pass

    def test_create_purchase_order_history(self):
        """Test case for create_purchase_order_history

        Allows you to create HistoryRecord for purchase orders  # noqa: E501
        """
        pass

    def test_create_receipt(self):
        """Test case for create_receipt

        Allows you to create draft expense claim receipts for any user  # noqa: E501
        """
        pass

    def test_create_receipt_attachment_by_file_name(self):
        """Test case for create_receipt_attachment_by_file_name

        Allows you to create Attachment on expense claim receipts by file name  # noqa: E501
        """
        pass

    def test_create_receipt_history(self):
        """Test case for create_receipt_history

        Allows you to retrieve a history records of an Receipt  # noqa: E501
        """
        pass

    def test_create_repeating_invoice_attachment_by_file_name(self):
        """Test case for create_repeating_invoice_attachment_by_file_name

        Allows you to create attachment on repeating invoices by file name  # noqa: E501
        """
        pass

    def test_create_repeating_invoice_history(self):
        """Test case for create_repeating_invoice_history

        Allows you to create history for a repeating invoice  # noqa: E501
        """
        pass

    def test_create_tax_rate(self):
        """Test case for create_tax_rate

        Allows you to create Tax Rates  # noqa: E501
        """
        pass

    def test_create_tracking_category(self):
        """Test case for create_tracking_category

        Allows you to create tracking categories  # noqa: E501
        """
        pass

    def test_create_tracking_options(self):
        """Test case for create_tracking_options

        Allows you to create options for a specified tracking category  # noqa: E501
        """
        pass

    def test_delete_account(self):
        """Test case for delete_account

        Allows you to delete a chart of accounts  # noqa: E501
        """
        pass

    def test_delete_contact_group_contact(self):
        """Test case for delete_contact_group_contact

        Allows you to delete a specific Contact from a Contract Group  # noqa: E501
        """
        pass

    def test_delete_contact_group_contacts(self):
        """Test case for delete_contact_group_contacts

        Allows you to delete  all Contacts from a Contract Group  # noqa: E501
        """
        pass

    def test_delete_item(self):
        """Test case for delete_item

        Allows you to delete a specified item  # noqa: E501
        """
        pass

    def test_delete_linked_transaction(self):
        """Test case for delete_linked_transaction

        Allows you to delete a specified linked transactions (billable expenses)  # noqa: E501
        """
        pass

    def test_delete_payment(self):
        """Test case for delete_payment

        Allows you to update a specified payment for invoices and credit notes  # noqa: E501
        """
        pass

    def test_delete_tracking_category(self):
        """Test case for delete_tracking_category

        Allows you to delete tracking categories  # noqa: E501
        """
        pass

    def test_delete_tracking_options(self):
        """Test case for delete_tracking_options

        Allows you to delete a specified option for a specified tracking category  # noqa: E501
        """
        pass

    def test_email_invoice(self):
        """Test case for email_invoice

        Allows you to email a copy of invoice to related Contact  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Allows you to retrieve a single chart of accounts  # noqa: E501
        """
        pass

    def test_get_account_attachment_by_file_name(self):
        """Test case for get_account_attachment_by_file_name

        Allows you to retrieve Attachment on Account by Filename  # noqa: E501
        """
        pass

    def test_get_account_attachment_by_id(self):
        """Test case for get_account_attachment_by_id

        Allows you to retrieve specific Attachment on Account  # noqa: E501
        """
        pass

    def test_get_account_attachments(self):
        """Test case for get_account_attachments

        Allows you to retrieve Attachments for accounts  # noqa: E501
        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        Allows you to retrieve the full chart of accounts  # noqa: E501
        """
        pass

    def test_get_bank_transaction(self):
        """Test case for get_bank_transaction

        Allows you to retrieve a single spend or receive money transaction  # noqa: E501
        """
        pass

    def test_get_bank_transaction_attachment_by_file_name(self):
        """Test case for get_bank_transaction_attachment_by_file_name

        Allows you to retrieve Attachments on BankTransaction by Filename  # noqa: E501
        """
        pass

    def test_get_bank_transaction_attachment_by_id(self):
        """Test case for get_bank_transaction_attachment_by_id

        Allows you to retrieve Attachments on a specific BankTransaction  # noqa: E501
        """
        pass

    def test_get_bank_transaction_attachments(self):
        """Test case for get_bank_transaction_attachments

        Allows you to retrieve any attachments to bank transactions  # noqa: E501
        """
        pass

    def test_get_bank_transactions(self):
        """Test case for get_bank_transactions

        Allows you to retrieve any spend or receive money transactions  # noqa: E501
        """
        pass

    def test_get_bank_transactions_history(self):
        """Test case for get_bank_transactions_history

        Allows you to retrieve history from a bank transactions  # noqa: E501
        """
        pass

    def test_get_bank_transfer(self):
        """Test case for get_bank_transfer

        Allows you to retrieve any bank transfers  # noqa: E501
        """
        pass

    def test_get_bank_transfer_attachment_by_file_name(self):
        """Test case for get_bank_transfer_attachment_by_file_name

        Allows you to retrieve Attachments on BankTransfer by file name  # noqa: E501
        """
        pass

    def test_get_bank_transfer_attachment_by_id(self):
        """Test case for get_bank_transfer_attachment_by_id

        Allows you to retrieve Attachments on BankTransfer  # noqa: E501
        """
        pass

    def test_get_bank_transfer_attachments(self):
        """Test case for get_bank_transfer_attachments

        Allows you to retrieve Attachments from  bank transfers  # noqa: E501
        """
        pass

    def test_get_bank_transfer_history(self):
        """Test case for get_bank_transfer_history

        Allows you to retrieve history from a bank transfers  # noqa: E501
        """
        pass

    def test_get_bank_transfers(self):
        """Test case for get_bank_transfers

        Allows you to retrieve all bank transfers  # noqa: E501
        """
        pass

    def test_get_batch_payment_history(self):
        """Test case for get_batch_payment_history

        Allows you to retrieve history from a Batch Payment  # noqa: E501
        """
        pass

    def test_get_batch_payments(self):
        """Test case for get_batch_payments

        Retrieve either one or many BatchPayments for invoices  # noqa: E501
        """
        pass

    def test_get_branding_theme(self):
        """Test case for get_branding_theme

        Allows you to retrieve a specific BrandingThemes  # noqa: E501
        """
        pass

    def test_get_branding_theme_payment_services(self):
        """Test case for get_branding_theme_payment_services

        Allows you to retrieve the Payment services for a Branding Theme  # noqa: E501
        """
        pass

    def test_get_branding_themes(self):
        """Test case for get_branding_themes

        Allows you to retrieve all the BrandingThemes  # noqa: E501
        """
        pass

    def test_get_contact(self):
        """Test case for get_contact

        Allows you to retrieve, add and update contacts in a Xero organisation  # noqa: E501
        """
        pass

    def test_get_contact_attachment_by_file_name(self):
        """Test case for get_contact_attachment_by_file_name

        Allows you to retrieve Attachments on Contacts by file name  # noqa: E501
        """
        pass

    def test_get_contact_attachment_by_id(self):
        """Test case for get_contact_attachment_by_id

        Allows you to retrieve Attachments on Contacts  # noqa: E501
        """
        pass

    def test_get_contact_attachments(self):
        """Test case for get_contact_attachments

        Allows you to retrieve, add and update contacts in a Xero organisation  # noqa: E501
        """
        pass

    def test_get_contact_cis_settings(self):
        """Test case for get_contact_cis_settings

        Allows you to retrieve CISSettings for a contact in a Xero organisation  # noqa: E501
        """
        pass

    def test_get_contact_group(self):
        """Test case for get_contact_group

        Allows you to retrieve a unique Contract Group by ID  # noqa: E501
        """
        pass

    def test_get_contact_groups(self):
        """Test case for get_contact_groups

        Allows you to retrieve the ContactID and Name of all the contacts in a contact group  # noqa: E501
        """
        pass

    def test_get_contact_history(self):
        """Test case for get_contact_history

        Allows you to retrieve a history records of an Contact  # noqa: E501
        """
        pass

    def test_get_contacts(self):
        """Test case for get_contacts

        Allows you to retrieve, add and update contacts in a Xero organisation  # noqa: E501
        """
        pass

    def test_get_credit_note(self):
        """Test case for get_credit_note

        Allows you to retrieve a specific credit note  # noqa: E501
        """
        pass

    def test_get_credit_note_as_pdf(self):
        """Test case for get_credit_note_as_pdf

        Allows you to retrieve Credit Note as PDF files  # noqa: E501
        """
        pass

    def test_get_credit_note_attachment_by_file_name(self):
        """Test case for get_credit_note_attachment_by_file_name

        Allows you to retrieve Attachments on CreditNote by file name  # noqa: E501
        """
        pass

    def test_get_credit_note_attachment_by_id(self):
        """Test case for get_credit_note_attachment_by_id

        Allows you to retrieve Attachments on CreditNote  # noqa: E501
        """
        pass

    def test_get_credit_note_attachments(self):
        """Test case for get_credit_note_attachments

        Allows you to retrieve Attachments for credit notes  # noqa: E501
        """
        pass

    def test_get_credit_note_history(self):
        """Test case for get_credit_note_history

        Allows you to retrieve a history records of an CreditNote  # noqa: E501
        """
        pass

    def test_get_credit_notes(self):
        """Test case for get_credit_notes

        Allows you to retrieve any credit notes  # noqa: E501
        """
        pass

    def test_get_currencies(self):
        """Test case for get_currencies

        Allows you to retrieve currencies for your organisation  # noqa: E501
        """
        pass

    def test_get_employee(self):
        """Test case for get_employee

        Allows you to retrieve a specific employee used in Xero payrun  # noqa: E501
        """
        pass

    def test_get_employees(self):
        """Test case for get_employees

        Allows you to retrieve employees used in Xero payrun  # noqa: E501
        """
        pass

    def test_get_expense_claim(self):
        """Test case for get_expense_claim

        Allows you to retrieve a specified expense claim  # noqa: E501
        """
        pass

    def test_get_expense_claim_history(self):
        """Test case for get_expense_claim_history

        Allows you to retrieve a history records of an ExpenseClaim  # noqa: E501
        """
        pass

    def test_get_expense_claims(self):
        """Test case for get_expense_claims

        Allows you to retrieve expense claims  # noqa: E501
        """
        pass

    def test_get_invoice(self):
        """Test case for get_invoice

        Allows you to retrieve a specified sales invoice or purchase bill  # noqa: E501
        """
        pass

    def test_get_invoice_as_pdf(self):
        """Test case for get_invoice_as_pdf

        Allows you to retrieve invoices or purchase bills as PDF files  # noqa: E501
        """
        pass

    def test_get_invoice_attachment_by_file_name(self):
        """Test case for get_invoice_attachment_by_file_name

        Allows you to retrieve Attachment on invoices or purchase bills by it's filename  # noqa: E501
        """
        pass

    def test_get_invoice_attachment_by_id(self):
        """Test case for get_invoice_attachment_by_id

        Allows you to retrieve a specified Attachment on invoices or purchase bills by it's ID  # noqa: E501
        """
        pass

    def test_get_invoice_attachments(self):
        """Test case for get_invoice_attachments

        Allows you to retrieve Attachments on invoices or purchase bills  # noqa: E501
        """
        pass

    def test_get_invoice_history(self):
        """Test case for get_invoice_history

        Allows you to retrieve a history records of an invoice  # noqa: E501
        """
        pass

    def test_get_invoice_reminders(self):
        """Test case for get_invoice_reminders

        Allows you to retrieve invoice reminder settings  # noqa: E501
        """
        pass

    def test_get_invoices(self):
        """Test case for get_invoices

        Allows you to retrieve any sales invoices or purchase bills  # noqa: E501
        """
        pass

    def test_get_item(self):
        """Test case for get_item

        Allows you to retrieve a specified item  # noqa: E501
        """
        pass

    def test_get_item_history(self):
        """Test case for get_item_history

        Allows you to retrieve history for items  # noqa: E501
        """
        pass

    def test_get_items(self):
        """Test case for get_items

        Allows you to retrieve any items  # noqa: E501
        """
        pass

    def test_get_journal(self):
        """Test case for get_journal

        Allows you to retrieve a specified journals.  # noqa: E501
        """
        pass

    def test_get_journals(self):
        """Test case for get_journals

        Allows you to retrieve any journals.  # noqa: E501
        """
        pass

    def test_get_linked_transaction(self):
        """Test case for get_linked_transaction

        Allows you to retrieve a specified linked transactions (billable expenses)  # noqa: E501
        """
        pass

    def test_get_linked_transactions(self):
        """Test case for get_linked_transactions

        Retrieve linked transactions (billable expenses)  # noqa: E501
        """
        pass

    def test_get_manual_journal(self):
        """Test case for get_manual_journal

        Allows you to retrieve a specified manual journals  # noqa: E501
        """
        pass

    def test_get_manual_journal_attachment_by_file_name(self):
        """Test case for get_manual_journal_attachment_by_file_name

        Allows you to retrieve specified Attachment on ManualJournal by file name  # noqa: E501
        """
        pass

    def test_get_manual_journal_attachment_by_id(self):
        """Test case for get_manual_journal_attachment_by_id

        Allows you to retrieve specified Attachment on ManualJournals  # noqa: E501
        """
        pass

    def test_get_manual_journal_attachments(self):
        """Test case for get_manual_journal_attachments

        Allows you to retrieve Attachment for manual journals  # noqa: E501
        """
        pass

    def test_get_manual_journals(self):
        """Test case for get_manual_journals

        Allows you to retrieve any manual journals  # noqa: E501
        """
        pass

    def test_get_online_invoice(self):
        """Test case for get_online_invoice

        Allows you to retrieve a URL to an online invoice  # noqa: E501
        """
        pass

    def test_get_organisation_cis_settings(self):
        """Test case for get_organisation_cis_settings

        Allows you To verify if an organisation is using contruction industry scheme, you can retrieve the CIS settings for the organistaion.  # noqa: E501
        """
        pass

    def test_get_organisations(self):
        """Test case for get_organisations

        Allows you to retrieve Organisation details  # noqa: E501
        """
        pass

    def test_get_overpayment(self):
        """Test case for get_overpayment

        Allows you to retrieve a specified overpayments  # noqa: E501
        """
        pass

    def test_get_overpayment_history(self):
        """Test case for get_overpayment_history

        Allows you to retrieve a history records of an Overpayment  # noqa: E501
        """
        pass

    def test_get_overpayments(self):
        """Test case for get_overpayments

        Allows you to retrieve overpayments  # noqa: E501
        """
        pass

    def test_get_payment(self):
        """Test case for get_payment

        Allows you to retrieve a specified payment for invoices and credit notes  # noqa: E501
        """
        pass

    def test_get_payment_history(self):
        """Test case for get_payment_history

        Allows you to retrieve history records of a payment  # noqa: E501
        """
        pass

    def test_get_payment_services(self):
        """Test case for get_payment_services

        Allows you to retrieve payment services  # noqa: E501
        """
        pass

    def test_get_payments(self):
        """Test case for get_payments

        Allows you to retrieve payments for invoices and credit notes  # noqa: E501
        """
        pass

    def test_get_prepayment(self):
        """Test case for get_prepayment

        Allows you to retrieve a specified prepayments  # noqa: E501
        """
        pass

    def test_get_prepayment_history(self):
        """Test case for get_prepayment_history

        Allows you to retrieve a history records of an Prepayment  # noqa: E501
        """
        pass

    def test_get_prepayments(self):
        """Test case for get_prepayments

        Allows you to retrieve prepayments  # noqa: E501
        """
        pass

    def test_get_purchase_order(self):
        """Test case for get_purchase_order

        Allows you to retrieve a specified purchase orders  # noqa: E501
        """
        pass

    def test_get_purchase_order_history(self):
        """Test case for get_purchase_order_history

        Allows you to retrieve history for PurchaseOrder  # noqa: E501
        """
        pass

    def test_get_purchase_orders(self):
        """Test case for get_purchase_orders

        Allows you to retrieve purchase orders  # noqa: E501
        """
        pass

    def test_get_receipt(self):
        """Test case for get_receipt

        Allows you to retrieve a specified draft expense claim receipts  # noqa: E501
        """
        pass

    def test_get_receipt_attachment_by_file_name(self):
        """Test case for get_receipt_attachment_by_file_name

        Allows you to retrieve Attachments on expense claim receipts by file name  # noqa: E501
        """
        pass

    def test_get_receipt_attachment_by_id(self):
        """Test case for get_receipt_attachment_by_id

        Allows you to retrieve Attachments on expense claim receipts by ID  # noqa: E501
        """
        pass

    def test_get_receipt_attachments(self):
        """Test case for get_receipt_attachments

        Allows you to retrieve Attachments for expense claim receipts  # noqa: E501
        """
        pass

    def test_get_receipt_history(self):
        """Test case for get_receipt_history

        Allows you to retrieve a history records of an Receipt  # noqa: E501
        """
        pass

    def test_get_receipts(self):
        """Test case for get_receipts

        Allows you to retrieve draft expense claim receipts for any user  # noqa: E501
        """
        pass

    def test_get_repeating_invoice(self):
        """Test case for get_repeating_invoice

        Allows you to retrieve a specified repeating invoice  # noqa: E501
        """
        pass

    def test_get_repeating_invoice_attachment_by_file_name(self):
        """Test case for get_repeating_invoice_attachment_by_file_name

        Allows you to retrieve specified attachment on repeating invoices by file name  # noqa: E501
        """
        pass

    def test_get_repeating_invoice_attachment_by_id(self):
        """Test case for get_repeating_invoice_attachment_by_id

        Allows you to retrieve a specified Attachments on repeating invoices  # noqa: E501
        """
        pass

    def test_get_repeating_invoice_attachments(self):
        """Test case for get_repeating_invoice_attachments

        Allows you to retrieve Attachments on repeating invoice  # noqa: E501
        """
        pass

    def test_get_repeating_invoice_history(self):
        """Test case for get_repeating_invoice_history

        Allows you to retrieve history for a repeating invoice  # noqa: E501
        """
        pass

    def test_get_repeating_invoices(self):
        """Test case for get_repeating_invoices

        Allows you to retrieve any repeating invoices  # noqa: E501
        """
        pass

    def test_get_report_aged_payables_by_contact(self):
        """Test case for get_report_aged_payables_by_contact

        Allows you to retrieve report for AgedPayablesByContact  # noqa: E501
        """
        pass

    def test_get_report_aged_receivables_by_contact(self):
        """Test case for get_report_aged_receivables_by_contact

        Allows you to retrieve report for AgedReceivablesByContact  # noqa: E501
        """
        pass

    def test_get_report_ba_sor_gst(self):
        """Test case for get_report_ba_sor_gst

        Allows you to retrieve report for BAS only valid for AU orgs  # noqa: E501
        """
        pass

    def test_get_report_ba_sor_gst_list(self):
        """Test case for get_report_ba_sor_gst_list

        Allows you to retrieve report for BAS only valid for AU orgs  # noqa: E501
        """
        pass

    def test_get_report_balance_sheet(self):
        """Test case for get_report_balance_sheet

        Allows you to retrieve report for BalanceSheet  # noqa: E501
        """
        pass

    def test_get_report_bank_summary(self):
        """Test case for get_report_bank_summary

        Allows you to retrieve report for BankSummary  # noqa: E501
        """
        pass

    def test_get_report_budget_summary(self):
        """Test case for get_report_budget_summary

        Allows you to retrieve report for Budget Summary  # noqa: E501
        """
        pass

    def test_get_report_executive_summary(self):
        """Test case for get_report_executive_summary

        Allows you to retrieve report for ExecutiveSummary  # noqa: E501
        """
        pass

    def test_get_report_profit_and_loss(self):
        """Test case for get_report_profit_and_loss

        Allows you to retrieve report for ProfitAndLoss  # noqa: E501
        """
        pass

    def test_get_report_ten_ninety_nine(self):
        """Test case for get_report_ten_ninety_nine

        Allows you to retrieve report for TenNinetyNine  # noqa: E501
        """
        pass

    def test_get_report_trial_balance(self):
        """Test case for get_report_trial_balance

        Allows you to retrieve report for TrialBalance  # noqa: E501
        """
        pass

    def test_get_tax_rates(self):
        """Test case for get_tax_rates

        Allows you to retrieve Tax Rates  # noqa: E501
        """
        pass

    def test_get_tracking_categories(self):
        """Test case for get_tracking_categories

        Allows you to retrieve tracking categories and options  # noqa: E501
        """
        pass

    def test_get_tracking_category(self):
        """Test case for get_tracking_category

        Allows you to retrieve tracking categories and options for specified category  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Allows you to retrieve a specified user  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Allows you to retrieve users  # noqa: E501
        """
        pass

    def test_update_account(self):
        """Test case for update_account

        Allows you to update a chart of accounts  # noqa: E501
        """
        pass

    def test_update_account_attachment_by_file_name(self):
        """Test case for update_account_attachment_by_file_name

        Allows you to update Attachment on Account by Filename  # noqa: E501
        """
        pass

    def test_update_bank_transaction(self):
        """Test case for update_bank_transaction

        Allows you to update a single spend or receive money transaction  # noqa: E501
        """
        pass

    def test_update_bank_transaction_attachment_by_file_name(self):
        """Test case for update_bank_transaction_attachment_by_file_name

        Allows you to update an Attachment on BankTransaction by Filename  # noqa: E501
        """
        pass

    def test_update_bank_transfer_attachment_by_file_name(self):
        """Test case for update_bank_transfer_attachment_by_file_name

        """
        pass

    def test_update_contact(self):
        """Test case for update_contact

        """
        pass

    def test_update_contact_attachment_by_file_name(self):
        """Test case for update_contact_attachment_by_file_name

        """
        pass

    def test_update_contact_group(self):
        """Test case for update_contact_group

        Allows you to update a Contract Group  # noqa: E501
        """
        pass

    def test_update_credit_note(self):
        """Test case for update_credit_note

        Allows you to update a specific credit note  # noqa: E501
        """
        pass

    def test_update_credit_note_attachment_by_file_name(self):
        """Test case for update_credit_note_attachment_by_file_name

        Allows you to update Attachments on CreditNote by file name  # noqa: E501
        """
        pass

    def test_update_employee(self):
        """Test case for update_employee

        Allows you to update a specific employee used in Xero payrun  # noqa: E501
        """
        pass

    def test_update_expense_claim(self):
        """Test case for update_expense_claim

        Allows you to update specified expense claims  # noqa: E501
        """
        pass

    def test_update_invoice(self):
        """Test case for update_invoice

        Allows you to update a specified sales invoices or purchase bills  # noqa: E501
        """
        pass

    def test_update_invoice_attachment_by_file_name(self):
        """Test case for update_invoice_attachment_by_file_name

        Allows you to update Attachment on invoices or purchase bills by it's filename  # noqa: E501
        """
        pass

    def test_update_item(self):
        """Test case for update_item

        Allows you to udpate a specified item  # noqa: E501
        """
        pass

    def test_update_linked_transaction(self):
        """Test case for update_linked_transaction

        Allows you to update a specified linked transactions (billable expenses)  # noqa: E501
        """
        pass

    def test_update_manual_journal(self):
        """Test case for update_manual_journal

        Allows you to update a specified manual journal  # noqa: E501
        """
        pass

    def test_update_manual_journal_attachment_by_file_name(self):
        """Test case for update_manual_journal_attachment_by_file_name

        Allows you to update a specified Attachment on ManualJournal by file name  # noqa: E501
        """
        pass

    def test_update_purchase_order(self):
        """Test case for update_purchase_order

        Allows you to update a specified purchase order  # noqa: E501
        """
        pass

    def test_update_receipt(self):
        """Test case for update_receipt

        Allows you to retrieve a specified draft expense claim receipts  # noqa: E501
        """
        pass

    def test_update_receipt_attachment_by_file_name(self):
        """Test case for update_receipt_attachment_by_file_name

        Allows you to update Attachment on expense claim receipts by file name  # noqa: E501
        """
        pass

    def test_update_repeating_invoice_attachment_by_file_name(self):
        """Test case for update_repeating_invoice_attachment_by_file_name

        Allows you to update specified attachment on repeating invoices by file name  # noqa: E501
        """
        pass

    def test_update_tax_rate(self):
        """Test case for update_tax_rate

        Allows you to update Tax Rates  # noqa: E501
        """
        pass

    def test_update_tracking_category(self):
        """Test case for update_tracking_category

        Allows you to update tracking categories  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
