# coding: utf-8

"""
    Accounting API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.prepayments import Prepayments  # noqa: E501
from openapi_client.rest import ApiException


class TestPrepayments(unittest.TestCase):
    """Prepayments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrepayments(self):
        """Test Prepayments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.prepayments.Prepayments()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
