# coding: utf-8

"""
    Accounting API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BankTransfers(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'bank_transfers': 'list[BankTransfer]'
    }

    attribute_map = {
        'bank_transfers': 'BankTransfers'
    }

    def __init__(self, bank_transfers=None):  # noqa: E501
        """BankTransfers - a model defined in OpenAPI"""  # noqa: E501

        self._bank_transfers = None
        self.discriminator = None

        if bank_transfers is not None:
            self.bank_transfers = bank_transfers

    @property
    def bank_transfers(self):
        """Gets the bank_transfers of this BankTransfers.  # noqa: E501


        :return: The bank_transfers of this BankTransfers.  # noqa: E501
        :rtype: list[BankTransfer]
        """
        return self._bank_transfers

    @bank_transfers.setter
    def bank_transfers(self, bank_transfers):
        """Sets the bank_transfers of this BankTransfers.


        :param bank_transfers: The bank_transfers of this BankTransfers.  # noqa: E501
        :type: list[BankTransfer]
        """

        self._bank_transfers = bank_transfers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BankTransfers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
