# coding: utf-8

"""
    Accounting API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BrandingThemes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'branding_themes': 'list[BrandingTheme]'
    }

    attribute_map = {
        'branding_themes': 'BrandingThemes'
    }

    def __init__(self, branding_themes=None):  # noqa: E501
        """BrandingThemes - a model defined in OpenAPI"""  # noqa: E501

        self._branding_themes = None
        self.discriminator = None

        if branding_themes is not None:
            self.branding_themes = branding_themes

    @property
    def branding_themes(self):
        """Gets the branding_themes of this BrandingThemes.  # noqa: E501


        :return: The branding_themes of this BrandingThemes.  # noqa: E501
        :rtype: list[BrandingTheme]
        """
        return self._branding_themes

    @branding_themes.setter
    def branding_themes(self, branding_themes):
        """Sets the branding_themes of this BrandingThemes.


        :param branding_themes: The branding_themes of this BrandingThemes.  # noqa: E501
        :type: list[BrandingTheme]
        """

        self._branding_themes = branding_themes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrandingThemes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
