# coding: utf-8

"""
    Accounting API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class LineItemTracking(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tracking_category_id': 'str',
        'name': 'str',
        'option': 'str'
    }

    attribute_map = {
        'tracking_category_id': 'TrackingCategoryID',
        'name': 'Name',
        'option': 'Option'
    }

    def __init__(self, tracking_category_id=None, name=None, option=None):  # noqa: E501
        """LineItemTracking - a model defined in OpenAPI"""  # noqa: E501

        self._tracking_category_id = None
        self._name = None
        self._option = None
        self.discriminator = None

        if tracking_category_id is not None:
            self.tracking_category_id = tracking_category_id
        if name is not None:
            self.name = name
        if option is not None:
            self.option = option

    @property
    def tracking_category_id(self):
        """Gets the tracking_category_id of this LineItemTracking.  # noqa: E501

        The Xero identifier for a tracking category  # noqa: E501

        :return: The tracking_category_id of this LineItemTracking.  # noqa: E501
        :rtype: str
        """
        return self._tracking_category_id

    @tracking_category_id.setter
    def tracking_category_id(self, tracking_category_id):
        """Sets the tracking_category_id of this LineItemTracking.

        The Xero identifier for a tracking category  # noqa: E501

        :param tracking_category_id: The tracking_category_id of this LineItemTracking.  # noqa: E501
        :type: str
        """

        self._tracking_category_id = tracking_category_id

    @property
    def name(self):
        """Gets the name of this LineItemTracking.  # noqa: E501

        The name of the tracking category  # noqa: E501

        :return: The name of this LineItemTracking.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LineItemTracking.

        The name of the tracking category  # noqa: E501

        :param name: The name of this LineItemTracking.  # noqa: E501
        :type: str
        """
        if name is not None and len(name) > 100:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501

        self._name = name

    @property
    def option(self):
        """Gets the option of this LineItemTracking.  # noqa: E501

        See Tracking Options  # noqa: E501

        :return: The option of this LineItemTracking.  # noqa: E501
        :rtype: str
        """
        return self._option

    @option.setter
    def option(self, option):
        """Sets the option of this LineItemTracking.

        See Tracking Options  # noqa: E501

        :param option: The option of this LineItemTracking.  # noqa: E501
        :type: str
        """

        self._option = option

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LineItemTracking):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
