# coding: utf-8

"""
    Accounting API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ManualJournals(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'manual_journals': 'list[ManualJournal]'
    }

    attribute_map = {
        'manual_journals': 'ManualJournals'
    }

    def __init__(self, manual_journals=None):  # noqa: E501
        """ManualJournals - a model defined in OpenAPI"""  # noqa: E501

        self._manual_journals = None
        self.discriminator = None

        if manual_journals is not None:
            self.manual_journals = manual_journals

    @property
    def manual_journals(self):
        """Gets the manual_journals of this ManualJournals.  # noqa: E501


        :return: The manual_journals of this ManualJournals.  # noqa: E501
        :rtype: list[ManualJournal]
        """
        return self._manual_journals

    @manual_journals.setter
    def manual_journals(self, manual_journals):
        """Sets the manual_journals of this ManualJournals.


        :param manual_journals: The manual_journals of this ManualJournals.  # noqa: E501
        :type: list[ManualJournal]
        """

        self._manual_journals = manual_journals

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ManualJournals):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
