# coding: utf-8

"""
    Accounting API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ReportCell(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'value': 'str',
        'attributes': 'list[ReportAttribute]'
    }

    attribute_map = {
        'value': 'Value',
        'attributes': 'Attributes'
    }

    def __init__(self, value=None, attributes=None):  # noqa: E501
        """ReportCell - a model defined in OpenAPI"""  # noqa: E501

        self._value = None
        self._attributes = None
        self.discriminator = None

        if value is not None:
            self.value = value
        if attributes is not None:
            self.attributes = attributes

    @property
    def value(self):
        """Gets the value of this ReportCell.  # noqa: E501


        :return: The value of this ReportCell.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ReportCell.


        :param value: The value of this ReportCell.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def attributes(self):
        """Gets the attributes of this ReportCell.  # noqa: E501


        :return: The attributes of this ReportCell.  # noqa: E501
        :rtype: list[ReportAttribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ReportCell.


        :param attributes: The attributes of this ReportCell.  # noqa: E501
        :type: list[ReportAttribute]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportCell):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
